name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm install
      
      - name: Run linter
        run: npm run lint

      - name: Run typechecker
        run: npm run typecheck

      - name: Run tests
        run: npm run test