name: doc preview

on:
  pull_request:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup vercel CLI
        run: npm install --global vercel@latest

      - name: Pull vercel environment
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project
        id: deploy
        run: |
          echo "DEPLOYEMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT

      - name: Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        with:
          temporaryPublicStorage: true
          budgetPath: ./doc/budget.json
          urls: |
            ${{steps.deploy.outputs.DEPLOYEMENT_URL}}
            ${{steps.deploy.outputs.DEPLOYEMENT_URL}}/en/doc@1.0.0/getting-started/blog-posts
